# Workflow name
name: Collector Auto Update

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  push:
    branches:
      - main
    paths:
      # To avoid unnecessary runs, the workflow is triggered on push only
      # if these specific files are changed.
      - 'config_collector.py'
      - 'requirements.txt'
      - 'text/sample_sources.txt'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-configs:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository's code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Set up the Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        # Caching dependencies to speed up subsequent runs
        cache: 'pip'

    # Step 3: Install dependencies from the requirements file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the main python script (using the correct filename)
    - name: Run Python Collector Script
      run: python config_collector.py

    # Step 5: Commit and push the generated files if there are any changes
    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update collector output [skip ci]"
        file_pattern: "output/*.txt"
        commit_user_name: "GitHub Actions Bot"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
